# Generated by Django 4.0.1 on 2022-01-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('by', models.CharField(max_length=200)),
                ('descendants', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kids', models.TextField(default='')),
                ('score', models.IntegerField()),
                ('text', models.TextField(blank=True)),
                ('time', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=200)),
                ('id_articles', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=200)),
                ('descendants', models.IntegerField(default=0)),
                ('id_articles', models.IntegerField(default=0)),
                ('kids', models.TextField(default='')),
                ('score', models.IntegerField(default=0)),
                ('text', models.TextField(blank=True)),
                ('time', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
    ]
