# Generated by Django 4.0.1 on 2022-01-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_ask_id_articles_alter_ask_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask',
            name='id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='id',
        ),
        migrations.RemoveField(
            model_name='story',
            name='id',
        ),
        migrations.AlterField(
            model_name='ask',
            name='id_articles',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='id_articles',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='id_articles',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
