# Generated by Django 4.0.1 on 2022-01-31 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_ask_id_remove_job_id_remove_story_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ask',
            options={'verbose_name': 'Ask', 'verbose_name_plural': 'Asks'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
    ]
